### ISSUE TITLE
Initial Login DashBoard - Cannot enter with default username and password

### ISSUE THREAD

**Issue by marcoczen** [havok89/Hoosk#12]
With regards to the above , i cannot login with default username admin and password  h00sk

Any hints ?

**Comment by havok89** [comment]
Is it giving the message that username or password is incorrect? if it isnt giving this error message and just going to a blank login form then it is an issue with how the cookie is being set.

As Hoosk is built on CodeIgniter then many solutions for cookie or set up problems for CodeIgniter will also work here.

check issue #2

**Comment by marcoczen** [comment]
Havok89, Checking ...

**Comment by marcoczen** [comment]
Side Note - I copied the hoosk cms files to our company's webhost. I CAN login with the default admin/h00sk username and password combo BUT after i save changes ( edited the home page content ) and logout to browse the changes i made - i get an error;


An Error Was Encountered
Unable to load the requested file: templates/header.php

**Comment by havok89** [comment]
Check the files uploaded for https://github.com/havok89/Hoosk/blob/master/hoosk/hoosk0/views/admin/header.php

and in each theme folder theres a /templates/header.php

**Comment by marcoczen** [comment]
Checking

**Comment by marcoczen** [comment]
in    public_html/hoosk/hoosk0/views/admin , i can see a header.php

inside  the themes folder, i can see subfolders ;

admin, blue, dark, orange, purple, red, turquoise

an inside , say subfolder , blue, i can see templates/header

**Comment by marcoczen** [comment]
Clarification - With regards to my localhost developemnt server,

when i login with demo / h00sk - i get error message in red box " The Username of Password enetered in incorrect"

when i login with admin/h00sk, i am just redirected back to the SAME login page. There is NO error message in a Red Box on top

**Comment by marcoczen** [comment]
Holy crap - clearing the cookie value in  hoosk/hoosk0/config/config.php as below DID it ...
$config['cookie_domain']	= "";     // no space inside the inverted commas.

So now I CAN login into the hoosk cms as the admin with default passwd h00sk. This issue SOLVED for my localhost development server.

Pending is ;

Sub_Issue B - Side Note - I copied the hoosk cms files to our company's webhost. I CAN login with the default admin/h00sk username and password combo BUT after i save changes ( edited the home page content ) and logout to browse the changes i made - i get an error;

An Error Was Encountered
Unable to load the requested file: templates/header.php

I open separate issue for this ?

**Comment by havok89** [comment]
I would try going to the settings page when logged in and selecting a new theme and saving again.
it uses the value saved in the database so that it knows what theme folder to use

**Comment by marcoczen** [comment]
Havok89, i went into the settings page of hoosk cms at the webhost and changed the theme from "admin" to "red"....

The error message ;

An Error Was Encountered
Unable to load the requested file: templates/header.php

is now GONE !

But, with the red theme , the banner etc on top is red ( so something is working ) , i do however get an error message;

Oops, there has been an error.
Sorry this page is currently unavailable.

**Comment by havok89** [comment]
Ill need to take a look at that, the admin theme shouldnt be selectable from there as it isnt for the front end of the site which is why it is missing the template files header etc

**Comment by marcoczen** [comment]
Roger that. Thanks.

With regards to the red theme ....

But, with the red theme , the banner etc on top is red ( so something is working ) , i do however get an error message;

  Oops, there has been an error.
  Sorry this page is currently unavailable.


Is that normal ?

**Comment by mohsen-sojoudi** [comment]
If you are using XAMPP or any local server Just add the following line in your index.php at the root folder
**session_start();**
