### ISSUE TITLE
Upload Site Logo with SVG files

### ISSUE THREAD

**Issue by WolfCodeRo** [havok89/Hoosk#13]
Hello,

How can I upload Site Logo with SVG files in Dashboard?

Than you!

**Comment by havok89** [comment]
Just now the only allowed filetypes are jpg, png and gif.

you can change this by altering the highlighted line here:
https://github.com/havok89/Hoosk/blob/master/hoosk/hoosk0/controllers/admin/Admin.php#L141

you can try changing 'gif|jpg|png' to 'gif|jpg|png|svg' or if that fails to work just allow all file types by changing it to '*'.
