### ISSUE TITLE
ADD Attachment in edit page

### ISSUE THREAD

**Issue by andreaaz** [havok89/Hoosk#15]
it's possible

**Comment by havok89** [comment]
how would this function for the front end and back end?

**Comment by andreaaz** [comment]
yes, but integrated with trevor

**Comment by havok89** [comment]
so like how the button functions but with file upload functionality

**Comment by andreaaz** [comment]
yes
to add an attachment to a content

**Comment by havok89** [comment]
I think I can probably do this with adding a file manager too, which will also work for adding images to pages/content.
Something like http://www.responsivefilemanager.com/ unless there is any other suggestions

**Comment by havok89** [comment]
Just an update, I am working on this and its almost ready to commit - can take a look at http://beta.hoosk.org its the same login as the demo site

**Comment by havok89** [comment]
File manager has been added, try out http://demo.hoosk.org has been commited to master but not as a release version yet

**Comment by andreaaz** [comment]
Tks 
but i can't see the filemanager in to  http://demo.hoosk.org

**Comment by havok89** [comment]
If you go to add a button, next to the URL box there is a link to a file button, it can take a few seconds to pop up when clicked. will look at adding a loading spinner or something
