### ISSUE TITLE
Error performing query

### ISSUE THREAD

**Issue by andikart** [havok89/Hoosk#16]
![hooks1](https://cloud.githubusercontent.com/assets/10099168/20640333/8da1b9fe-b40d-11e6-81fb-c24f4a7f10d3.PNG)

and i try import manual the sql file to my phpmy admin
![hooks2](https://cloud.githubusercontent.com/assets/10099168/20640337/aeacfce4-b40d-11e6-8089-0dbe60a3295d.PNG)

**Comment by havok89** [comment]
Hi,

Ive downloaded and done a fresh install from the github master with no problems. The install script fails if any of the tables already exist.

The SQL file contains a "~" at the end of each line to help the install script run it, I know i need to look at a better way of doing this but if you do a search and remove for "~" then manually import it should work, best to empty the database first

**Comment by andikart** [comment]
is still Error performing query after i delete all "~" in SQL file and empety my database.
![hooks after delete](https://cloud.githubusercontent.com/assets/10099168/20642971/96055d3e-b44f-11e6-819c-a1445bfb04c2.PNG)

![hooks after delete 2](https://cloud.githubusercontent.com/assets/10099168/20642978/aa9a3666-b44f-11e6-8cd3-5404b3dbd222.PNG)

**Comment by andikart** [comment]
Thanks for your help my problem is done i create manually a database :)
