### ISSUE TITLE
Published for Posts as well

### ISSUE THREAD

**Issue by miscs** [havok89/Hoosk#18]
Hi, 

nice project - just downloaded it and playing around. Looks very cool!

What do you think about having a published flag (yes/no) for posts as well? Also it would be great to have this flag shown in the overview table of pages/posts to easily see which pages/posts are published.

Regards
miscs

**Comment by havok89** [comment]
Hi,

I do agree with this, can't think how I forgot to include it in the posts section.
Adding a flag for published is a good idea too.

Will look into it for the next update

**Comment by havok89** [comment]
Published flags have been added in latest update for posts and pages

https://github.com/havok89/Hoosk/releases/tag/v1.5.5
