### ISSUE TITLE
Provide JSON output as well

### ISSUE THREAD

**Issue by miscs** [havok89/Hoosk#19]
Do you have any plans to provide JSON output as well?

Maybe like http://hoosk.org/json/article/hoosk-15-update--rss-feeds-and-more

**Comment by havok89** [comment]
This is something that could be implemented, what could be the use of it?
If I can understand more how it would be used that would help with how I can add it

**Comment by miscs** [comment]
The idea was to use the JSON output for showing articles inside a native app. Seems like this would be a good idea, because the JSON is nicely structured an could be stored (offline-reading) and rendered on app-site as well...

**Comment by havok89** [comment]
This is next on my list for new features

**Comment by miscs** [comment]
cool, looking forward to it :)

**Comment by havok89** [comment]
Hey,

how does this look?

http://beta.hoosk.org/feed/json

It includes post title, url, date posted, excerpt, content in HTML format and since the content editor stored it in JSON format that is included too.

I havent pushed it to master yet still have some other bits im working on
