### ISSUE TITLE
Login demo code

### ISSUE THREAD

**Issue by Wmas** [havok89/Hoosk#2]
I have just successfully installed the cms. 

The welcome page say:

Login details: 
Username - demo
Password - h00sk

Unfortunately this is not working. Also having a look at the database I see that the username in the user table is "admin" and not "demo". 

Also using "admin" as username would give an error.

Which credential must to be used to access the CMS.

I appreciate your help with this issue.

Franco

**Comment by Wmas** [comment]
I sow your demo online. This is just a nice CMS. I like your modern bootstrap approach and this is a very promising application.
Anyway, after spending a few hours trying to login without any success. I just installed the CMS again.

Unfortunately with the same issue: The Username of Password entered is incorrect.

Please help!

Franco

**Comment by havok89** [comment]
When you say using "admin" gives an error, is it just that you cant log in or does it give an error message?

If its an error message then I have a fix where you change the .htaccess file for another one as it is an issue that happens on some servers.

**Comment by Wmas** [comment]
Thank you for your reply.

I try to login with:
username: admin
password: h00sk (two zeros, I have also tried with two 'OO')

I didn't get any error just : The Username of Password entered is incorrect.

Thanks.

**Comment by havok89** [comment]
From what I can see by googling it is an issue with running on localhost

(http://stackoverflow.com/questions/5884916/codeigniter-sessions-wont-stick-on-localhost-mamp)

The line it refers to in the second answer is:

https://github.com/havok89/Hoosk/blob/master/hoosk/hoosk0/config/config.php#L383

Try setting it to being blank.

**Comment by Wmas** [comment]
This was indeed! I can now login.
Has this some consequences setting the cookies?
Thanks for your help. This is for sure a nice and modern CMS. I think this will become a good used one in the codeigniter community.

Regards

Franco

**Comment by adepeter4lyf** [comment]
Hello, after successfull installation of hoosk, I can't access the admin panel after inputting demo as username and password. The page just keep saying refreshing itself when I login

**Comment by mohsen-sojoudi** [comment]
If you are using XAMPP or any local server Just add the following line in your index.php at the root folder
**session_start();**
