### ISSUE TITLE
admin arena white page issue

### ISSUE THREAD

**Issue by PowerChaos** [havok89/Hoosk#23]
hi,
i got a fresh install of hoosk 1.5 but after install the admin arena only displays a white page
on same config i installed version 1.4 and then the admin arena works perfect

also few suggestions
installer still works with mysql instead mysqli/pdo
so it trows out errors xD

Greets From PowerChaos

**Comment by havok89** [comment]
The install script has now been updated to mysqli. I am unsure on the issue with with the white page, are you running it on a local server?

**Comment by PowerChaos** [comment]
no, i run it on cpanel ( version 62 , centos 7 ) 
i tried it on differend compiled ways of apache ( because a other script dit not work eather, buildercms ) 
i used apache prefork as dso (then the other script works ...execution permissions  ) and apache event with fastcgiD ( daemon ) but then the ohter script dit not work 
anyway
version 1.5 dit ,not work on both settings , when version 1.4 does work on both versions

my guess is that it has to do with the new ajax session check , as after login ( session set  ) it shows only the white page and nothing more ( refuse to execute any kind of html output ? ) 

it doesnt shows a error log and it doesnt shows any error code , so i guess it need to be the fresh added ajax code for the session 

or in worste case ( a other error i found ) is that the RSS feed does  NOT work ( error 500 ) 
probaly because it trows a 500 return error that the script stops working and prevent to show anything as the script can not execute ( that new added RSS feed at the home of the admin arena ) 

The error 500 is probably trown  where the script try to curl to get the markup of the xml file, but i would think that it would provide then any logs of the execution error

i founded the rss bug when i was looking manual into the files
https://github.com/havok89/Hoosk/commit/887f2fa1d2e30fe71a2a8e65ac1c193f727839a5

>  $this->data['recenltyUpdated'] = $this->Hoosk_model->getUpdatedPages();
>  $this->load->library('rssparser');
>  $this->rssparser->set_feed_url('http://hoosk.org/feed/rss');
>  $this->rssparser->set_cache_life(30);
>  $this->data['hooskFeed'] = $this->rssparser->getFeed(3);

here is the feed response ( xml reader plugin for chrome xD ) 
> <h4>A PHP Error was encountered</h4>
> <p>Severity: Notice</p>
> <p>Message:  Undefined index: author</p>
> <p>Filename: feed/rss.php</p>
> <p>Line Number: 26</p>
> <p>Backtrace:</p>
> <p style="margin-left:10px">			File:  /home/theloxie/public_html/hooskorg/theme/hoosk2015/feed/rss.php
> <br/>
> 			Line: 26
> <br/>
> 			Function: _error_handler			</p>
> <p style="margin-left:10px">			File:  /home/theloxie/public_html/hooskorg/hoosk/hoosk0/core/MY_Loader.php
> <br/>
> 			Line: 128
>  ......

Greets From PowerChaos

**Comment by havok89** [comment]
It does sound like it could be to do with the RSS then,

If you open your index.php file at line 64 you can change "production" to "development" and it should output any errors it encounters.

https://github.com/havok89/Hoosk/blob/master/index.php

**Comment by PowerChaos** [comment]
Thank you
i also dit some more tests and at current moment i can reproduce the error
it counts for all versions
seems it was just unlucky to hit the 500 page at that time

if you change the feed url to hoosker.org then it perfectly reproduce the error
`Message: file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known`

can you put a fix in the script so the controllers doesnt break on warning and continue , specialy with remote url files ?

also htacces need a small change ( for fastcgiD ) 
`RewriteRule .* index.php?/$0 [PT,L]`
it need to have that ? after index.php or rewrite does not work xD

Greets From PowerChaos

**Comment by havok89** [comment]
Have added a fix for the error message in relation to the RSS feed and added a RSS flag in the index.php, can set it to false to disable the RSS feed display.
https://github.com/havok89/Hoosk/releases/tag/v1.5.6

Just noticed your point about the htaccess, will add into the next update
