### ISSUE TITLE
Database Structure

### ISSUE THREAD

**Issue by PowerChaos** [havok89/Hoosk#24]
hi,
is there any reason why you do not use unique collums  in the database ( for some tables ) ?

without unique collums is it complicated to manual edit the pages (phpmyadmin for example) 
also it is not possible yet to add colors and rich html text to the pages with out manual editing the database

can you fix the unique collums in the database please ?
its located in content and navigation

i also use version 1.4 as 1.5 refuse to work ( admin arena )

also it would be nice to include a small tutorial how to make custom pages like a contact form , as that does not exist yet ( exept the news.php page ) 

iframe does also NOT work , as soon you put a iframe in it it fails to safe and it also fails to work like it need to be

after beein used to this system is it still a nice system , but it is heavy limited at this moment for full use :(

Greets From PowerChaos

**Comment by havok89** [comment]
Unique columns have been addressed in latest update https://github.com/havok89/Hoosk/releases/tag/v1.5.5 , I was unable to find any issues with the iframe block.
make sure you put the full <iframe></iframe> code into the block.

I will investigate a way for simple text colouring in the content editor but at the moment I will be keeping it a simple editor.
