### ISSUE TITLE
Post and Pages

### ISSUE THREAD

**Issue by Afdhal-Mahdi** [havok89/Hoosk#26]
Can not save and update to post or pages Hoosk Version 1.5.6, do notice All fields marked with * are required!, when all the forms have been filled. tq
screenshot http://imgh.us/save_2.jpg

**Comment by havok89** [comment]
looks like the routes is missing or the install isnt configured properly. should use the latest version

**Comment by Afdhal-Mahdi** [comment]
Has succeeded, I replaced
in view post_new.php and page_new.php
before : url: 'admin/check/session',
to : url: '<?php echo base_url();?>admin/check/session',
