### ISSUE TITLE
There are error when post is about more than 10

### ISSUE THREAD

**Issue by aswzen** [havok89/Hoosk#27]
http://beta.hoosk.org/category/uncategorized-asd/10

There are error when post is about more than 10 in a **category**

when i press button next it will go to error page

**Comment by havok89** [comment]
Have fixed this issue in latest release, you just need to add one line see here

https://github.com/havok89/Hoosk/commit/e2a33e512646dcad9fb01d4e2c4a82058b6bfa9e
