### ISSUE TITLE
cannot login after installation

### ISSUE THREAD

**Issue by nikhil167** [havok89/Hoosk#28]
I installed hoosk and this "installation completed" page came up with a login button, but clicking on that button >  "This site can’t be reached demohoosk’s server DNS address could not be found." Page is lost
what i did wrong? i'm a beginner please do help

**Comment by havok89** [comment]
Hey

Please check your config.php file that was created by the install script and ensure your domain is correct, I just tested doing a fresh install and ran into no issues here.

What set up are you installing it on?

**Comment by nikhil167** [comment]
i'm setting it on my localhost using wamp.
 i think this is making problem > "Site URL (without http:// or trailing slash)"
i have given my folder name in the root here.

**Comment by havok89** [comment]
Make sure the theme folder has extracted correctly, it should have 2 themes in it, the admin and the default theme.

I will try installing this weekend using wamp as there has been a few people having issues with it.

**Comment by nikhil167** [comment]
Thanks mate,
looking forward to it. Well there is 2 themes in it admin and dark, not default.

**Comment by havok89** [comment]
That is fine as long as tehre is something as well as admin folder in there, i meant dark not default lol.
It must be an issue with it not being able to read whats in that folder

**Comment by nikhil167** [comment]
Hi havok89, Did you check it.

**Comment by havok89** [comment]
I managed to get it running fine in wamp - I installed the latest version of wamp and copied the files to:

C:\wamp64\www\hoosk

When visiting localhost/hoosk it would install but not work so what I had to do was set up a virtual host in wamp - it was simple to do:

Go to the wamp homepage by visiting localhost then under Tools on the bottom left hand side there is "**Add a Virtual Host**" click on it.

-For "**Name of the Virtual Host**" I put hoosktest.com
-You can skip the middle option - "**If you want to use VirtualHost by IP: local IP 127.x.y.z Optional**"
- For "**Complete absolute path of the VirtualHost folder**" I put C:\wamp64\www\hoosk which is where i put the hoosk files.

after saving this it prompts you to restart the DNS which you can do by rightclicking the wamp icon and going to tools -> restart dns

After this if i visit hoosktest.com in my browser it loads the local hoosk version on wamp and installs and works fine - just set the url during install to what you made your virtual host name (mine being hoosktest.com)

Hope that helps you!

**Comment by nikhil167** [comment]
Many Thanks Mate, Worked Perfectly !!

**Comment by hs364** [comment]
Hello, login can't jump
