### ISSUE TITLE
How to search a post in All Post? 

### ISSUE THREAD

**Issue by aswzen** [havok89/Hoosk#29]
I posted more than 100 dummy posts,
Now i have difficulties to find some post and i didn't see any search feature.

And then the pagination buttons looks very primitive, can you style it?

Thank you

Regards,
Git

**Comment by havok89** [comment]
Hey, a search function for the posts and pages sections is on my list, will try get it in the next update.

are the primitive pagination buttons the ones on the front end of the website or the admin dashboard?

**Comment by havok89** [comment]
This has been added in the new update and can be tested in the demo site
