### ISSUE TITLE
Relative Links

### ISSUE THREAD

**Issue by lucasjmiles** [havok89/Hoosk#30]
I am installing Hoosk onto my local machine and working from 127.0.0.1/example

however, all of your relative links are not working correctly... they are reverting the url back to just 127,0,0,1 without the folder name at the end? anyway to fix this?

**Comment by havok89** [comment]
If you are using Wamp or Mamp or similar try the solution posted here:

https://github.com/havok89/Hoosk/issues/28#issuecomment-291448438

tldr; you need to set up a virtual host.
