### ISSUE TITLE
Error when creating/editing content in news, pages, etc

### ISSUE THREAD

**Issue by milstrike** [havok89/Hoosk#35]
So, the problem occured when I try to save the content (in news, pages, etc). After I click save button, then the page is not working.

![screenshot 10](https://user-images.githubusercontent.com/6276159/28349013-81b897a0-6c6a-11e7-83b5-59be785a9280.png)

![screenshot 11](https://user-images.githubusercontent.com/6276159/28349028-922ef642-6c6a-11e7-8d79-31dd6e6ddcab.png)

![screenshot 12](https://user-images.githubusercontent.com/6276159/28349040-9c671db0-6c6a-11e7-984a-4d7998defe2c.png)

is there any idea for this..?

**Comment by havok89** [comment]
Are you able to send me FTP details so I can check it out? can send them over to callum@standupguy.co.uk

**Comment by milstrike** [comment]
@havok89 I just sent an email to you. Thank You for your help.
