### ISSUE TITLE
cannot create new user

### ISSUE THREAD

**Issue by assurur** [havok89/Hoosk#37]
Error Number: 1364

Field 'RS' doesn't have a default value

INSERT INTO `hoosk_user` (`userName`, `email`, `password`) VALUES ('test', 'test@test.com', '22d61613a8f7120dff19ee54ac97ac48')

Filename: C:/wamp64/www/test/hoosk/hoosk0/models/Hoosk_model.php

Line Number: 128

**Comment by kingdominc** [comment]
I also ran into this problem. Fixed by modifying Hoosk_model.php and modifying the method: createUser

```php
    function createUser() {
        // Create the user account
        $data = array(
            'userName' => $this->input->post('username'),
            'email' => $this->input->post('email'),
            'password' => md5($this->input->post('password').SALT),
            'RS' => '' //value is required - set to an empty string
        );
        $this->db->insert('hoosk_user', $data);
    }
```
