### ISSUE TITLE
admin page not working

### ISSUE THREAD

**Issue by ThomasVandenabeele** [havok89/Hoosk#43]
I'm running an apache server with a new Hoosk installation behind a reverse proxy. 
All requests are redirected to https. After installation I needed to manually change the BASE_URL in the generated config.php file because http was saved in the file.
So, the front-end is working currently... everything fine.

But I'm not able to display the admin page. When I login, Hooks returns me an empty page.
Can I see some log files or errors for hooks?
Does someone maybe know how to fix this and tell me if this problem is related to the reverse proxy?

**Comment by daguswijaya** [comment]
Switch your ENVIRONMENT to development to find out what goes wrong. In my case, the problem solved by installing php-xml (php5.6-xml) on my server.

**Comment by a6smile** [comment]
Hoosk admin login does not work on php 7.0 above, to make it work switch you server environment to php 5.6

**Comment by mohsen-sojoudi** [comment]
If you are using XAMPP or any local server Just add the following line in your index.php at the root folder
**session_start();**

**Comment by callumb** [comment]
@a6smile that’s not really a fix but a nasty hack

**Comment by havok89** [comment]
/late reply 

If you update the system folder to the latest version of codeigniter it will fix issues. The issues only happen with the version of codeigniter included and PHP 7+

Using session start is a hacky fix as it starts a PHP session when the system uses codeigniter sessions so may cause further issues elsewhere
