### ISSUE TITLE
XSS on Hoosk v1.7.0

### ISSUE THREAD

**Issue by Hu3sky** [havok89/Hoosk#47]
the xss is on the page 'admin/pages/new'，add a text new page, fill the `<img src=1 onerror=alert(1)>` in the 'Navigation Title* (this is displayed on navigation menus)' field
![tim 20180819142717](https://user-images.githubusercontent.com/37403964/44306229-0d2d0200-a3bd-11e8-955b-2cf90d2e18ac.png)
![tim 20180819142913](https://user-images.githubusercontent.com/37403964/44306230-0dc59880-a3bd-11e8-9f17-11cbd79bcd21.png)

**Comment by havok89** [comment]
I was sure all the inputs were sanitising data but appears not. I suppose at this point an attacker would already have access to your admin dashboard so the site would already be compromised. 

I'll try get time to fix it in the next few days!
