### ISSUE TITLE
Admin login doesn't work on SSL

### ISSUE THREAD

**Issue by dotcomdude** [havok89/Hoosk#7]
I love Hoosk!

Trying to use it on my first 'real' website and have to use it with an SSL installed.  Changed the root domain to include https which corrected lots of insecure resource warnings, but now I can't log in as the admin user.  Is that a real bug?

**Comment by havok89** [comment]
Hey,

are you able to send some FTP details to callum@hoosk.org and I can take a look see whats happening, or not happening.

Thanks,
Callum

**Comment by dotcomdude** [comment]
Have emailed you - thanks for such a prompt response!

**Comment by havok89** [comment]
Issue was to do with the Cookie URL and has been sorted, there appears to be no other problems with using it with an SSL.
