### ISSUE TITLE
How to install Hoosk with apache2

### ISSUE THREAD

**Issue by zcfrank1st** [havok89/Hoosk#8]
I copied Hoosk to the /var/www/html directory and run installing , every thing seemed ok, but when it finished installing, I clicked the login button, it printed 404 not found the /admin url ... how could I fix it? Thank you！

**Comment by isaiahfrom3r** [comment]
You need a root folder .htaccess. 

try this 



<IfModule mod_rewrite.c>

    # Set this to /dev for the dev link or / for the live version:
    RewriteEngine On
    RewriteBase /
    
    # Checks to see if the user is attempting to access a valid file,
    # if not it sends the request to index.php:
    RewriteCond %{REQUEST_FILENAME} !-f
       RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php?/$1 [PT,L]
    
</IfModule>
